In [1]:
import pandas as pd

#Cargamos los Diccionarios de atención

In [2]:
df_anexo1 = pd.read_excel("Diccionario.xlsx")
df_anexo1

    ID CAUSA                                         GLOSACAUSA
0          1            SECCIÓN 1. TOTAL ATENCIONES DE URGENCIA
1          2                  TOTAL CAUSAS SISTEMA RESPIRATORIO
2          3           Bronquitis/bronquiolitis aguda (J20-J21)
3          4                                Influenza (J09-J11)
4          5                                 Neumonía (J12-J18)
5          6  Otra causa respiratoria (J22, J30-J39, J47, J6...
6          7                        CAUSAS SISTEMA RESPIRATORIO
7          8                                 - LAS DEMÁS CAUSAS
8         10                                 IRA Alta (J00-J06)
9         11             Crisis obstructiva bronquial (J40-J46)
10        12                  TOTAL CAUSAS SISTEMA CIRCULATORIO
11        13                            Infarto agudo miocardio
12        14                      Accidente vascular encefálico
13        15                                Crisis hipertensiva
14        16                                     Arritmia grave
15        17                         Otras causas circulatorias
16        18                TOTAL TRAUMATISMOS Y ENVENENAMIENTO
17        19                            Accidentes del tránsito
18        20                              Otras causas externas
19        21                                 TOTAL DEMÁS CAUSAS
20        22                      - CAUSAS SISTEMA CIRCULATORIO
21        23                   - TRAUMATISMOS Y ENVENENAMIENTOS
22        24                               CIRUGÍAS DE URGENCIA
23        25              SECCIÓN 2. TOTAL DE HOSPITALIZACIONES
24        26  SECCIÓN 3. PACIENTES EN ESPERA DE HOSPITALIZAC...
25        27             Pacientes en espera de hospitalización
26        28  Pacientes en espera de hospitalización que esp...
27        29                            DIARREA AGUDA (A00-A09)
28        30                 Covid-19, Virus identificado U07.1
29        31              Covid-19, Virus no identificado U07.2
30        32               - COVID-19, VIRUS IDENTIFICADO U07.1
31        33            - COVID-19, VIRUS NO IDENTIFICADO U07.2
32        34                                      TOTAL DEMANDA
33        35  Lesiones autoinfligidas intencionalmente (X60-...
34        36      TOTAL CAUSAS DE TRASTORNOS MENTALES (F00-F99)
35        37                           Ideación Suicida (R45.8)
36        38  Trastornos mentales y del comportamiento debid...
37        39         Trastornos del Humor (Afectivos) (F30-F39)
38        40  Trastornos neuróticos, trastornos relacionados...
39        41  Otros trastornos mentales no contenidos en las...
40        42         - CAUSAS POR TRASTORNOS MENTALES (F00-F99)

In [62]:
causas_resp = [3,4,5,6,7]
comunas = ["Osorno", "Temuco", "Valdivia", "Concepcion", "Chiguayante"]

#Cargamos los set de datos del 2020 hasta el 2025

In [40]:
df2025 = pd.read_csv("AtencionesUrgencia2025.csv", encoding='latin1', sep=';')
df2024 = pd.read_csv("AtencionesUrgencia2024.csv", encoding='latin1', sep=';')
df2023 = pd.read_csv("AtencionesUrgencia2023.csv", encoding='latin1', sep=';')
df2022 = pd.read_csv("AtencionesUrgencia2022_Mapeado.csv", encoding="utf-8")
df2021 = pd.read_csv("AtencionesUrgencia2021_1_Mapeado.csv", encoding="utf-8")
df2020 = pd.read_csv("AtencionesUrgencia2020_Mapeado.csv", encoding="utf-8")

C:\Users\mda30\AppData\Local\Temp\ipykernel_26952\3578016128.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df2025 = pd.read_csv("AtencionesUrgencia2025.csv", encoding='latin1', sep=';')
C:\Users\mda30\AppData\Local\Temp\ipykernel_26952\3578016128.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df2024 = pd.read_csv("AtencionesUrgencia2024.csv", encoding='latin1', sep=';')

In [41]:
df2022.head()

,Unnamed: 0,IdEstablecimiento,NEstablecimiento,IdCausa,GlosaCausa,Total,Menores_1,De_1_a_4,De_5_a_14,De_15_a_64,De_65_y_mas,fecha,semana,GLOSATIPOESTABLECIMIENTO,GLOSATIPOATENCION,GlosaTipoCampana,ComunaGlosa,RegionGlosa
0,0,18106,Hospital de Lota,1,SECCIÓN 1. TOTAL ATENCIONES DE URGENCIA,68,1,3,10,43,11,01/01/2022,52,Hospital,Indiferenciado,Ninguna,Lota,Región del Bíobío
1,1,3910,SAR Alemania,1,SECCIÓN 1. TOTAL ATENCIONES DE URGENCIA,80,1,5,10,55,9,01/01/2022,52,SAR,Indiferenciado,Ninguna,Calama,Región de Antofagasta
2,2,14822,SAR Padre Manuel Villaseca,1,SECCIÓN 1. TOTAL ATENCIONES DE URGENCIA,121,2,8,14,77,20,01/01/2022,52,SAR,Indiferenciado,Ninguna,Puente Alto,Región Metropolitana de Santiago
3,3,11903,SAR Enfermera Sofía Pincheira,1,SECCIÓN 1. TOTAL ATENCIONES DE URGENCIA,110,0,5,11,77,17,01/01/2022,52,SAR,Indiferenciado,Ninguna,Cerrillos,Región Metropolitana de Santiago
4,4,13814,SAPU Cóndores de Chile,1,SECCIÓN 1. TOTAL ATENCIONES DE URGENCIA,89,0,4,8,63,14,01/01/2022,52,SAPU,Indiferenciado,Sapu Metropolitana,El Bosque,Región Metropolitana de Santiago

In [ ]:
print(df2022['ColumnaGlosa'].unique())

['De Arica y Parinacota' 'De Tarapacá' 'De Antofagasta'
 'Metropolitana de Santiago' 'De Valparaíso' nan 'De La Araucanía'
 'De Atacama' 'De Coquimbo' "Del Libertador B. O'Higgins" 'Del Maule'
 'De Ñuble' 'Del Bíobío' 'De Los Lagos'
 'De Magallanes y de La Antártica Chilena' 'De Los Ríos'
 'De Aisén del Gral. C. Ibáñez del Campo']

#Filtramos por causas respiratorias

In [63]:
df2020_filtrado = df2020[df2020["IdCausa"].isin(causas_resp) & df2020["ComunaGlosa"].isin(comunas)]
df2021_1_filtrado = df2021[df2021["IdCausa"].isin(causas_resp) & df2021["ComunaGlosa"].isin(comunas)]
df2022_filtrado = df2022[df2022["IdCausa"].isin(causas_resp) & df2022["ComunaGlosa"].isin(comunas)]
df2023_filtrado = df2023[df2023["IdCausa"].isin(causas_resp) & df2023["NombreComuna"].isin(comunas)]
df2024_filtrado = df2024[df2024["IdCausa"].isin(causas_resp) & df2024["NombreComuna"].isin(comunas)]
df2025_filtrado = df2025[df2025["IdCausa"].isin(causas_resp) & df2025["NombreComuna"].isin(comunas)]

In [ ]:
print(df2020_filtrado["Total"].sum())
print(df2021_1_filtrado["Total"].sum())
print(df2022_filtrado["Total"].sum())
print(df2023_filtrado["Total"].sum())
print(df2024_filtrado["Total"].sum())
print(df2025_filtrado["Total"].sum())
13830
21047
65867
80314
87142
86990

15854
22928
71796
80314
87142
86990

In [ ]:
df2020_filtrado.tocsv("AtencionesRespiratorias/AtencionesRespiratorias2020.csv", index=False)
df2021_1_filtrado.to_csv("AtencionesRespiratorias/AtencionesRespiratorias2021.csv", index=False)
df2022_filtrado.to_csv("AtencionesRespiratorias/AtencionesRespiratorias2022.csv", index=False)
df2023_filtrado.to_csv("AtencionesRespiratorias/AtencionesRespiratorias2023.csv", index=False)
df2024_filtrado.to_csv("AtencionesRespiratorias/AtencionesRespiratorias2024.csv", index=False)
df2025_filtrado.to_csv("AtencionesRespiratorias/AtencionesRespiratorias2025.csv", index=False)